#!/usr/bin/perl 
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
#Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
#
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.


for($i=1;$i<5000;$i++){
	$t{$i} = $i*($i+1)/2;
	$p{$i} = $i*(3*$i-1)/2;
	$h{$i} = $i*(2*$i-1);
}

foreach $t_key(keys %t){
	$flag =0;
	foreach $p_key(keys %p){
		if($t{$t_key} == $h{$p_key})
		{
			$flag = 1;
		}
                if($t{$t_key} == $p{$p_key} && $flag==1)
                {
                        print "key: ",$t_key;
                        
                }
	}
}
lab1:
